### ISSUE TITLE
CUDA Out-of-Memory Error on Linux with LLM Integration - VM Environment

### ISSUE THREAD

**Issue by jonasschultheiss** [VikParuchuri/marker#711]
# CUDA Out-of-Memory Error on Linux with LLM Integration - VM Environment

## Summary
Marker v1.7.3 fails with unrealistic CUDA memory allocation attempts when using `--use_llm` flag on Linux VM environments, while basic marker functionality works perfectly. This appears to be a **Linux-specific bug** affecting multiple users.

## Environment Details
- **OS**: Ubuntu with VM/PCIe passthrough
- **GPU**: NVIDIA GeForce GTX 1070 (8GB VRAM)
- **Driver**: 570.133.07
- **CUDA**: 12.6 (PyTorch 2.7.0+cu126)
- **Python**: 3.10
- **marker-pdf**: 1.7.3 (upgraded from 1.6.2)
- **surya-ocr**: 0.14.2 (upgraded from 0.13.1)

### Working 2 weeks ago:
```bash
marker "$INPUT_DIR" \
  --output_dir "$OUTPUT_DIR" \
  --workers 1 \
  --llm_service "marker.services.ollama.OllamaService" \
  --ollama_base_url "http://localhost:11434" \
  --ollama_model "gemma3:1b-it-qat" \
  --strip_existing_ocr \
  --force_ocr \
  --redo_inline_math \
  --use_llm \
  --output_format markdown \
  --format_lines
```

### Current Behavior:
**Error**: `CUDA out of memory. Tried to allocate 24.13 GiB. GPU 0 has a total capacity of 7.92 GiB`

Even with **6.8GB free VRAM** (Ollama using only 1.2GB), marker attempts to allocate 24GB on an 8GB GPU.

## Comparison with GitHub Issue #710

This is **identical** to [issue #710](https://github.com/VikParuchuri/marker/issues/710):
- **Same error pattern**: Unrealistic VRAM allocation (19.05 GiB on 10.57 GiB GPU vs our 24.13 GiB on 7.92 GiB GPU)
- **Linux-specific**: Works on Windows, fails on Ubuntu/Linux environments  
- **Similar hardware**: RTX 2080 Ti (11GB) vs GTX 1070 (8GB)
- **Same versions**: marker 1.7.2/1.7.3, PyTorch 2.7.0+cu128/cu126
- **VM environments**: Both running in virtualized environments

This confirms it's a **known Linux-specific bug** in marker's memory allocation with LLM mode.

### ✅ **What Works:**
1. **Basic marker without LLM**: Processes perfectly in ~27s
2. **Ollama standalone**: Works fine on GPU (confirmed functional)
3. **Hardware health**: nvidia-smi shows normal operation

### ❌ **What Fails:**
1. **LLM integration**: Causes unrealistic memory allocation attempts
2. **PyTorch multiprocessing**: `RuntimeError: pidfd_getfd: Operation not permitted` in VM
3. **OCR with LLM**: Very slow processing (208s/iteration) when combining flags

### ⚠️ **Partial Success with Workarounds:**
Using advanced memory management can make LLM work:
```bash
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export CUDA_LAUNCH_BLOCKING=1
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256
export CUDA_VISIBLE_DEVICES=0
```

**Result**: LLM processing works (~29s) but with:
- Persistent Ollama 500 Server Error warnings (handled gracefully)
- Memory fragmentation still occurs
- OCR flags cause extreme slowdown

## Ollama 500 Server Error Issue

Even with the working memory management configuration, **persistent 500 Server Error warnings** occur during LLM processing:

```
2025-05-20 19:44:05,463 [WARNING] marker: Ollama inference failed: 500 Server Error: Internal Server Error for url: http://localhost:11434/api/generate
2025-05-20 19:44:05,463 [WARNING] marker: Ollama inference failed: 500 Server Error: Internal Server Error for url: http://localhost:11434/api/generate
2025-05-20 19:44:07,460 [WARNING] marker: Ollama inference failed: 500 Server Error: Internal Server Error for url: http://localhost:11434/api/generate
```

**Key Observations:**
- **Ollama works standalone**: Direct `ollama run` commands work perfectly
- **VM-specific issue**: Likely related to communication between marker and Ollama in virtualized environments
- **Graceful handling**: Marker continues processing despite warnings
- **Output quality**: Final results are still enhanced by LLM processing
- **Frequency**: Multiple 500 errors per document processing session

This suggests **additional VM communication issues** beyond just the memory allocation problem.

## Memory Analysis

| Configuration | Ollama VRAM | Available VRAM | Marker Allocation Attempt | Result |
|---------------|-------------|----------------|---------------------------|---------|
| gemma3:4b-it-qat | 4.3GB | 3.7GB | 24.13 GiB | ❌ CUDA OOM |
| gemma3:1b-it-qat | 1.2GB | 6.8GB | 24.13 GiB | ❌ CUDA OOM |
| No LLM | 0GB | 8GB | Normal | ✅ Works |
| LLM + Memory Mgmt | 1.2GB | 6.8GB | Managed | ✅ Works with warnings |

## Root Cause Analysis

1. **Linux VM multiprocessing issues** with PyTorch CUDA memory allocation
2. **Memory allocator bug** - requests impossible amounts regardless of available VRAM
3. **Default memory management** too aggressive for virtualized environments  
4. **Ollama communication issues** in VM causing 500 errors during LLM calls

## Expected Behavior

LLM integration should:
1. **Respect available VRAM** - Not attempt 24GB allocation on 8GB GPU
2. **Work in Linux VMs** - Same as Windows environments per issue #710
3. **Handle OCR flags efficiently** - Not cause 10x performance degradation

### **Immediate (for users):**
```bash
# Workaround: Advanced memory management
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export CUDA_LAUNCH_BLOCKING=1
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256
export CUDA_VISIBLE_DEVICES=0

# Use smaller model
--ollama_model "gemma3:1b-it-qat"

# Avoid combining OCR flags with LLM for performance
```

### **Long-term (for developers):**
1. **Fix memory allocation logic** - Respect actual GPU memory limits
2. **Improve Linux VM compatibility** - Address multiprocessing issues
3. **Optimize OCR+LLM interaction** - Reduce performance impact
4. **Better error handling** - Graceful fallback when allocation fails

## Test Case to Reproduce

1. **Setup**: Linux VM with GPU passthrough, marker 1.7.3, Ollama with any model
2. **Command**: Any `marker_single` or `marker` with `--use_llm` flag
3. **Expected**: CUDA out of memory with unrealistic allocation attempt
4. **Actual**: Should process normally within available VRAM limits

**Comment by SirNoName2705** [comment]
> [@jonasschultheiss](https://github.com/jonasschultheiss) Thanks for the very detailed report! One question - When you say "Basic marker without LLM: Processes perfectly in ~27s", what is the exact option list you are using here? Is `format_lines` set here as well?
> 
> This will help me debug and get this fixed for you soon :)

This solved the problem for me at least.

**Comment by anwar3606** [comment]
> export CUDA_LAUNCH_BLOCKING=1
> export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256
> export CUDA_VISIBLE_DEVICES=0

@jonasschultheiss thanks for this. I had an issue where a large pdf failed because of OOM with 8GB VRAM. Was able to run just fine with this.
